version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "3000"
    volumes:
      - ./src:/snappfood/src
      - ./public:/snappfood/public
      - .env:/snappfood/.env

  nginx:
    image: nginx:1.21.0-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
